USE DATABASE CAMPAIGN;

USE SCHEMA CAMPAIGN.PERF;


-- CAMPAIGN OVERVIEW

-- 1. Average duration by campaign type
SELECT 
    CAMPAIGN_TYPE, 
    AVG(DURATION) FROM MARKPERF
GROUP BY CAMPAIGN_TYPE
ORDER BY AVG(DURATION) DESC;

-- 2. Average duration by channel
SELECT 
    CHANNEL_USED, 
    AVG(DURATION) FROM MARKPERF
GROUP BY CHANNEL_USED
ORDER BY AVG(DURATION) DESC;

-- 3. Total campaign spend by company and campaign type
SELECT 
    COMPANY,
    CAMPAIGN_TYPE, 
    COUNT(CAMPAIGN_ID) AS NO_OF_CAMPAIGN, 
    SUM(ACQUISITION_COST) AS TOTAL_COST
FROM MARKPERF
GROUP BY COMPANY, CAMPAIGN_TYPE;

-- 4. Campaign type with highest average ROI
SELECT 
    CAMPAIGN_TYPE, 
    ROUND(AVG(ROI),3) AS AVG_ROI
FROM MARKPERF
GROUP BY CAMPAIGN_TYPE
ORDER BY AVG(ROI) DESC;

-- 5. Company with lowest ROI campaigns
SELECT 
    COMPANY, 
    ROUND(AVG(ROI),3) AS AVG_ROI
FROM MARKPERF
GROUP BY COMPANY
ORDER BY AVG(ROI) ASC;


-- DEMOGRAPHIC OVERVIEW

-- 6. Gender targeted campaign
SELECT 
    TARGET_GENDER, 
    COUNT(*) AS GENDER_COUNT
FROM MARKPERF
GROUP BY TARGET_GENDER
HAVING TARGET_GENDER = 'Men' OR TARGET_GENDER = 'Women';

-- 7. Gender-targeted campaigns with higher average engagement scores
SELECT 
    CAMPAIGN_TYPE, 
    TARGET_GENDER, 
    AVG(ENGAGEMENT_SCORE) AS AVG_ENG_SCORE
FROM MARKPERF
GROUP BY CAMPAIGN_TYPE, TARGET_GENDER
ORDER BY AVG(ENGAGEMENT_SCORE) DESC;

-- 8. Distribution of ROI accross top customer segments
SELECT 
    TOP 3 CUSTOMER_SEGMENTATION,
    ROUND(AVG(ROI),4) AS AVG_ROI
FROM MARKPERF
GROUP BY CUSTOMER_SEGMENTATION
ORDER BY AVG(ROI) DESC;


-- LOCATION OVERVIEW

-- 9. Location with most campaigns
SELECT 
    LOCATION, 
    COUNT(CAMPAIGN_ID) AS COUNT_CAMPAIGN
FROM MARKPERF
GROUP BY LOCATION
ORDER BY COUNT(CAMPAIGN_ID) DESC;

-- 10. Top performing locations based on ROI
SELECT LOCATION, ROUND(AVG(ROI),4) AS AVG_ROI
FROM MARKPERF
GROUP BY LOCATION
ORDER BY AVG(ROI) DESC;


-- TIME-SERIES & TREND OVERVIEW

-- 11. Month-wise average acquisition cost

WITH MONTHLY_COST AS (
SELECT 
    DATE_PART(month, CAMPAIGN_DATE) AS MONTH_NUM, 
    CAMPAIGN_MONTH, 
    AVG(ACQUISITION_COST) AS AVG_COST
FROM MARKPERF
GROUP BY DATE_PART(month, CAMPAIGN_DATE), CAMPAIGN_MONTH
ORDER BY DATE_PART(month,CAMPAIGN_DATE)
)
SELECT 
    CAMPAIGN_MONTH, 
    ROUND(AVG_COST,2)
FROM MONTHLY_COST;

-- 12. Compare previous and current month acquisition costs

WITH MONTHLY_COST AS (
SELECT 
    DATE_PART(month, CAMPAIGN_DATE) AS MONTH_NUM, 
    CAMPAIGN_MONTH, 
    AVG(ACQUISITION_COST) AS AVG_COST,
FROM MARKPERF
GROUP BY DATE_PART(month, CAMPAIGN_DATE), CAMPAIGN_MONTH
ORDER BY DATE_PART(month,CAMPAIGN_DATE))

SELECT 
    CAMPAIGN_MONTH, 
    ROUND(AVG_COST,2) AS CURRENT_MONTH, 
    LAG(AVG_COST) OVER(ORDER BY MONTH_NUM) AS PREVIOUS_MONTH
FROM MONTHLY_COST;

-- 13. Month-wise campaign impression

WITH MONTHLY_IMP AS (
SELECT 
    DATE_PART(month, CAMPAIGN_DATE), 
    CAMPAIGN_MONTH, 
    AVG(IMPRESSIONS) AS AVG_IMP
FROM MARKPERF
GROUP BY DATE_PART(month, CAMPAIGN_DATE), CAMPAIGN_MONTH
ORDER BY DATE_PART(month,CAMPAIGN_DATE)
)
SELECT 
    CAMPAIGN_MONTH, 
    ROUND(AVG_IMP,2) AS AVG_IMPRESSION
FROM MONTHLY_IMP;

-- 14. TOP 3 Month with highest total acquisition cost

WITH MONTHLY_ACQ AS (
SELECT 
    DATE_PART(month, CAMPAIGN_DATE), 
    CAMPAIGN_MONTH, 
    SUM(ACQUISITION_COST) AS TOTAL_ACQ_COST 
FROM MARKPERF
GROUP BY DATE_PART(month, CAMPAIGN_DATE), CAMPAIGN_MONTH
ORDER BY DATE_PART(month, CAMPAIGN_DATE)
)
SELECT TOP 3 CAMPAIGN_MONTH, TOTAL_ACQ_COST
FROM MONTHLY_ACQ
ORDER BY TOTAL_ACQ_COST DESC;

-- 15. Trend of engagement score over the months

WITH MONTHLY_ENG AS (
SELECT 
    DATE_PART(month, CAMPAIGN_DATE), 
    CAMPAIGN_MONTH, 
    ROUND(AVG(ENGAGEMENT_SCORE),3) AS AVG_ENG
FROM MARKPERF
GROUP BY DATE_PART(month, CAMPAIGN_DATE), CAMPAIGN_MONTH
ORDER BY DATE_PART(month,CAMPAIGN_DATE)
)
SELECT 
    CAMPAIGN_MONTH, 
    AVG_ENG
FROM MONTHLY_ENG;

-- 16. Running total of acquisition cost per month

WITH RUNNING_TOTAL AS (
SELECT 
    DATE_PART(month, CAMPAIGN_DATE) AS MONTH_NUM, 
    CAMPAIGN_MONTH, 
    SUM(ACQUISITION_COST) AS CURR_MONTH,
FROM MARKPERF
GROUP BY DATE_PART(month, CAMPAIGN_DATE), CAMPAIGN_MONTH
ORDER BY DATE_PART(month,CAMPAIGN_DATE)
)
SELECT 
    MONTH_NUM,
    CAMPAIGN_MONTH, 
    CURR_MONTH,
    SUM(CURR_MONTH) OVER(ORDER BY MONTH_NUM) AS RUNNINGTOT
FROM
    RUNNING_TOTAL;

-- 17. Monthly difference on acquisation cost

WITH ACQ_DIFF AS (
SELECT DATE_PART(month, CAMPAIGN_DATE) AS MONTH_NUM, 
        CAMPAIGN_MONTH,
        SUM(ACQUISITION_COST) AS TOTAL_ACQ,
FROM MARKPERF
GROUP BY DATE_PART(month, CAMPAIGN_DATE), CAMPAIGN_MONTH
ORDER BY DATE_PART(month, CAMPAIGN_DATE))
SELECT 
    MONTH_NUM,
    CAMPAIGN_MONTH,
    TOTAL_ACQ,
    COALESCE(TOTAL_ACQ - LAG(TOTAL_ACQ) OVER (ORDER BY MONTH_NUM),0) AS MONTHLY_DIFF
FROM ACQ_DIFF;


-- CONVERSION & ENGAGEMENT OVERVIEW

-- 18. Click-to-conversion rate by campaign type

WITH CLICK_CONVERSION AS (
SELECT 
    CAMPAIGN_TYPE, 
    ROUND(SUM(CLICKS)/SUM(IMPRESSIONS) *100,3) AS CLICK_TO_CONVERSION
FROM MARKPERF
GROUP BY CAMPAIGN_TYPE
)
SELECT 
    CAMPAIGN_TYPE, 
    CONCAT((CLICK_TO_CONVERSION::VARCHAR(20)), '%') AS CLICK_TO_CONVERSION_RATE
FROM CLICK_CONVERSION
ORDER BY CLICK_TO_CONVERSION DESC;

-- 19. Average conversion rate by channel

SELECT 
    CHANNEL_USED, 
    AVG(CONVERSION_RATE) AS AVG_CONVERSION
FROM MARKPERF
GROUP BY CHANNEL_USED;

-- 20. Customer segment with highest click through rates
SELECT 
    CUSTOMER_SEGMENTATION, 
    AVG(CLICKS) AS AVG_CLICKS
FROM MARKPERF
GROUP BY CUSTOMER_SEGMENTATION
ORDER BY AVG(CLICKS) DESC;

-- 21. Max duration and impression by campaign-channel combination
SELECT 
    CAMPAIGN_ID, 
    CHANNEL_USED, 
    MAX(DURATION) AS MAX_DURATION, 
    MAX(IMPRESSIONS) AS MAX_IMP
FROM MARKPERF
GROUP BY CAMPAIGN_ID, CHANNEL_USED;

 -- 22. For each company, how did ROI change from one campaign to the next?

WITH DIFF_ROI AS (
SELECT 
    COMPANY,
    CAMPAIGN_TYPE,
    AVG(ROI) AS AVG_ROI
FROM MARKPERF
GROUP BY COMPANY, CAMPAIGN_TYPE
)
SELECT
    COMPANY,
    CAMPAIGN_TYPE,
    COALESCE(AVG_ROI - LAG(AVG_ROI) OVER (PARTITION BY COMPANY ORDER BY CAMPAIGN_TYPE),0) AS ROI_CHANGE
FROM DIFF_ROI;
 
-- 23. What is the rank of campaign types per channel based on average conversion rate?

SELECT 
    CHANNEL_USED,
    CAMPAIGN_TYPE,
    AVG(CONVERSION_RATE) AS AVG_CR,
    RANK() OVER (PARTITION BY CHANNEL_USED ORDER BY AVG_CR DESC) AS RANK_CR
FROM MARKPERF
GROUP BY CHANNEL_USED, CAMPAIGN_TYPE;